# Generated by Django 3.2.4 on 2021-06-28 19:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=100, verbose_name='Başlık - DE')),
                ('title_en', models.CharField(max_length=100, verbose_name='Başlık - EN')),
                ('content_de', ckeditor.fields.RichTextField(verbose_name='İçerik - DE')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='İçerik - EN')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Resim')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Haberler',
                'ordering': ['-id'],
            },
        ),
    ]
