# Generated by Django 5.0 on 2023-12-15 20:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automatic_Doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=150, verbose_name='Ürün İsmi - DE')),
                ('title_en', models.CharField(max_length=150, verbose_name='Ürün İsmi - EN')),
                ('product_type', models.CharField(max_length=150, verbose_name='Ürün Tipi')),
                ('content_de', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklamaları - DE')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklamaları - EN')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('image_de', models.ImageField(upload_to='', verbose_name='Ürün Resmi - DE')),
                ('image_en', models.ImageField(blank=True, upload_to='', verbose_name='Ürün Resmi - EN (Zorunlu Değil)')),
                ('spec_file_de', models.FileField(blank=True, upload_to='', verbose_name='Teknik Özellikler Dosyası (Pdf) - DE')),
                ('spec_file_en', models.FileField(blank=True, upload_to='', verbose_name='Teknik Özellikler Dosyası (Pdf) - EN')),
                ('catalog_file_de', models.FileField(blank=True, upload_to='', verbose_name='Ürün Kataloğu (Pdf) - DE')),
                ('catalog_file_en', models.FileField(blank=True, upload_to='', verbose_name='Ürün Kataloğu (Pdf) - EN')),
            ],
            options={
                'verbose_name_plural': 'Otomatik Kapılar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Failure_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Adı Soyadı')),
                ('company', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('email', models.EmailField(max_length=200, verbose_name="Email'i")),
                ('phone_number', models.CharField(max_length=200, verbose_name='Telefon Numarası')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('door_model', models.CharField(max_length=200, verbose_name='Kapı Türü')),
                ('trademark', models.CharField(max_length=200, verbose_name='Model')),
                ('fault', models.TextField(verbose_name='fault')),
            ],
            options={
                'verbose_name_plural': 'Arıza Bildirimleri',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Hospital_Doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=150, verbose_name='Ürün İsmi - DE')),
                ('title_en', models.CharField(max_length=150, verbose_name='Ürün İsmi - EN')),
                ('product_type', models.CharField(max_length=150, verbose_name='Ürün Tipi')),
                ('content_de', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklamaları - DE')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklamaları - EN')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('image_de', models.ImageField(upload_to='', verbose_name='Ürün Resmi - DE')),
                ('image_en', models.ImageField(blank=True, upload_to='', verbose_name='Ürün Resmi - EN (Zorunlu Değil)')),
                ('spec_file_de', models.FileField(blank=True, upload_to='', verbose_name='Teknik Özellikler Dosyası (Pdf) - DE')),
                ('spec_file_en', models.FileField(blank=True, upload_to='', verbose_name='Teknik Özellikler Dosyası (Pdf) - EN')),
                ('catalog_file_de', models.FileField(blank=True, upload_to='', verbose_name='Ürün Kataloğu (Pdf) - DE')),
                ('catalog_file_en', models.FileField(blank=True, upload_to='', verbose_name='Ürün Kataloğu (Pdf) - EN')),
            ],
            options={
                'verbose_name_plural': 'Hastane Kapıları',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Request_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name="Gönderen Email'i")),
                ('full_name', models.CharField(max_length=200, verbose_name='Gönderen Adı Soyadı')),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name_plural': 'Gelen İstekler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Security_Doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=150, verbose_name='Ürün İsmi - DE')),
                ('title_en', models.CharField(max_length=150, verbose_name='Ürün İsmi - EN')),
                ('product_type', models.CharField(max_length=150, verbose_name='Ürün Tipi')),
                ('content_de', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklamaları - DE')),
                ('content_en', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklamaları - EN')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('image_de', models.ImageField(upload_to='', verbose_name='Ürün Resmi - DE')),
                ('image_en', models.ImageField(blank=True, upload_to='', verbose_name='Ürün Resmi - EN (Zorunlu Değil)')),
                ('spec_file_de', models.FileField(blank=True, upload_to='', verbose_name='Teknik Özellikler Dosyası (Pdf) - DE')),
                ('spec_file_en', models.FileField(blank=True, upload_to='', verbose_name='Teknik Özellikler Dosyası (Pdf) - EN')),
                ('catalog_file_de', models.FileField(blank=True, upload_to='', verbose_name='Ürün Kataloğu (Pdf) - DE')),
                ('catalog_file_en', models.FileField(blank=True, upload_to='', verbose_name='Ürün Kataloğu (Pdf) - EN')),
            ],
            options={
                'verbose_name_plural': 'Security Kapıları',
                'ordering': ['-id'],
            },
        ),
    ]
